---
sidebar: sidebar 
permalink: ai-policy.html 
---
= ネットアップのテクニカルドキュメントに記載されているAI生成コンテンツの使用を禁止するポリシー
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ネットアップでは、お客様のために正確で関連性が高く有用な技術文書を作成、公開、保守するにあたり、従業員、請負業者、パートナーの専門知識を高く評価しています。AIで生成されたコンテンツを使用すると、これらの価値が損なわれ、ドキュメントの整合性と正確性が損なわれる可能性があると考えています。そのため、ネットアップのポリシーは、人間による検証と検証が行われていないAI生成コンテンツの公開を禁止することです。この環境 のすべてのテクニカルドキュメントは、docs.netapp.comで公開されています。このポリシーは、販売する製品のコードの記述に言語モデルを使用することを禁止するネットアップのポリシーに類似しており、その内容が拡張されています。

NetAppDocsに投稿するすべての人は、次のポリシーに従うことを期待しています。

* AIから生成されたお客様向けドキュメント（ネットアップ製品の使用方法）を、人手によるレビューと検証なしに公開することは認めていません。これには、docs.netapp.comで公開されている書面資料、グラフィック、マルチメディア、またはその他の資料が含まれます。docs.netapp.comで公開されているすべてのコンテンツは、ヒューマンコンテンツ作成者によって検証および検証されなければなりません。
* docs.netapp.comのコンテンツ作成者の役割の一部には、スタイルガイドとコントリビューターガイドの遵守が含まれています。これには、AI生成コンテンツの最新の開発内容と、ネットアップの技術ドキュメントに与える影響に関する最新情報の把握も含まれます。
* すべての従業員、請負業者、およびパートナーは、本ポリシーを遵守することが求められます。違反が繰り返されると、オーサリング権限が中断される可能性があります。


NetAppDocsの作成者は、次の点に留意する必要があります。

* Microsoft 365 Co-pilotなど、作業用コンピュータにインストールしたソフトウェアに組み込まれたAIベースのコンテンツ生成テクノロジはすべて、支援テクノロジをホストする企業にデータを送信します。リリースされていない製品機能の仕様を含むが、これに限定されない会社の機密コンテンツで、このような技術を促してはなりません。
* 以前にリリースされていない**製品、製品のバージョン、または製品内の機能の技術文書を生成または編集するために、パブリックAIテクノロジを使用しないでください。
* 新しいテクニカルドキュメントの著作権はネットアップ社内に保持する必要があり、正式な製品リリース日および関連するテクニカルドキュメントが発行されるまでは、ネットアップ社外のAISと共有しないでください。
* 機密文書や新規作成されたコンテンツをAI (ChatGPTまたはその他のツール)に送信しないでください。ChatGPTに入力されたすべての情報は、そのトレーニングデータセットの一部となり、OpenAIのプロパティとなり、それらとそのユーザーが使用できるようになります。これらのデータの多くは一般公開されていますが、独自のIPでモデルをトレーニングすることは避けたいと考えています。

