---
sidebar: sidebar 
permalink: ai-policy.html 
---
= ネットアップのテクニカルドキュメントに記載されているAI生成コンテンツの使用を禁止するポリシー
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ネットアップでは、従業員、請負業者、パートナーの創造性と専門知識を大切にし、お客様のために正確で関連性の高い有用な技術文書を作成、公開、維持しています。AIで生成されたコンテンツを使用すると、これらの価値が損なわれ、ドキュメントの整合性と正確性が損なわれる可能性があると考えています。そのため、ネットアップのポリシーは、docs.netapp.comで公開されているすべての技術ドキュメントでAI生成コンテンツを使用することを禁止することです。このポリシーは、販売する製品のコードの記述に言語モデルを使用することを禁止するネットアップのポリシーに類似しており、その内容が拡張されています。

NetAppDocsに投稿するすべての人は、次のポリシーに従うことを期待しています。

. * AI生成コンテンツの使用禁止:*当社がお客様向けに作成する技術文書にAI生成コンテンツを使用することはできません。これには、netapp.comで公開されている書面資料、グラフィック、マルチメディア、またはその他の資料が含まれます。docs.netapp.comで公開されるすべてのコンテンツは、当社の従業員、請負業者、またはパートナーが独自の創造性、専門知識、経験を使用して作成する必要があります。
. *教育とトレーニング:*当社は、従業員、請負業者、パートナーに対して、AI生成コンテンツの使用および技術文書で許可されていない理由について、定期的にトレーニングと教育を提供しています。ネットアップでは、ネットアップの関係者全員に、AIで生成されたコンテンツの最新の開発内容と、ネットアップの技術ドキュメントへの影響を常に把握しておくことを推奨しています。
. *コンプライアンスおよび報告：*すべての従業員、請負業者、およびパートナーは、このポリシーを遵守する責任があります。本ポリシーへの違反または違反の疑いがある場合は、ただちにネットアップ法務部に報告して調査を依頼する必要があります。


NetAppDocsの作成者は、次の点に留意する必要があります。

* 以前にリリースされていない製品、製品のバージョン、または製品内の機能のテクニカルドキュメントを生成または編集するためにAIを使用しないでください。
* 新しいテクニカルドキュメントの著作権はネットアップ社内に保持する必要があり、正式な製品リリース日および関連するテクニカルドキュメントが発行されるまでは、ネットアップ社外のAISと共有しないでください。
* 機密文書、新しいコンテンツ、またはURLを含む2021年以降に作成されたコンテンツを、AI (ChatGPTまたはその他のツール)に送信しないでください。ChatGPTに入力されたすべての情報は、そのトレーニングデータセットの一部となり、OpenAIのプロパティとなり、それらとそのユーザーが使用できるようになります。これらのデータの多くは一般公開されていますが、独自のIPでモデルをトレーニングすることは避けたいと考えています。

