---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    langs: ja-jp,us-en,zh-cn
  langs: ja-jp,us-en,zh-cn
sidebar:
  entries:
  - title: コンテンツを投稿します
    url: "/index.html"
  - title: ネットアップのドキュメントの形式
    url: "/style.html"
  - title: AsciiDoc リファレンス
    url: "/asciidoc_syntax.html"
