---
sidebar: sidebar 
permalink: style.html 
---
= ネットアップのドキュメントのスタイルガイド
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
私たちのスタイルは会話型で共感的ですが、プロ意識を維持し、その点に到達しています。ネットアップのドキュメントのコンテンツを作成する際は、次のガイドラインに従ってください。



== 書き込みの変換

プロフェッショナルな同僚に何かを説明しているときは、話しているように書きます。会話の中で文章を書くと、聞き手とつながりやすくなります。


TIP: 大きな声で書き出してください。アメリカの小説家およびスクリーンライター、 Elmore Leonard が言ったように、「それが執筆のように聞こえたら、私はそれを書き直します。」。

|===
| 形式が多すぎます | カジュアルすぎます | 私たちのスタイル 


| Cloud Tiering で問題が発生した場合は、クラスタダッシュボードに健全性ステータスを表示して、エラーの原因を特定できます。ヘルスは、 ONTAP システムとサービスコネクタのステータスを表します。 | 失敗が起こったときは、楽しみではありません。ただし、クラスタダッシュボードを確認して、何が起こったのか、何が影響を受けたのかを確認してください。 | 障害が発生すると、 Cloud Tiering は、クラスタダッシュボードに「失敗」正常性ステータスを表示します。ステータスを表示して、障害に関する情報を確認します。 


| クラウド階層化の料金はさまざまな方法で支払うことができます。従量課金制のサブスクリプションを使用してクラウド階層化の料金を支払うか、 ONTAP 階層化ライセンスを使用して料金を支払うか、または両方を組み合わせて料金を支払うことができます。Cloud Manager からライセンスを取得することはできません。設定するには、 Cloud Tiering サービスに直接アクセスする必要があります。 | クラウド階層化の料金を支払う方法は 3 通りあります。もちろん、従量課金制のサブスクリプションだけでなく、 ONTAP の階層化ライセンス、あるいはその両方を組み合わせたライセンスも必要です。ただし、 Cloud Manager からライセンスを取得することはできません。 Cloud Tiering サービスに直接アクセスして、ライセンスを設定してください。 | 従量課金制のサブスクリプション、 ONTAP 階層化ライセンス、またはその両方を組み合わせて使用して、クラウド階層化の料金を支払うことができます。ライセンスは Cloud Manager からは取得できませんが、直接 Cloud Tiering サービスにアクセスして設定できます。 


| ストレージをプロビジョニングする前に、 Cloud Manager から ONTAP クラスタを検出する必要があります。検出が完了したら、作業環境を開いてストレージをプロビジョニングする必要があります。 | まず、 Cloud Manager から ONTAP クラスタを検出し、次に作業環境を開いてストレージのプロビジョニングを開始します。簡単！ | Cloud Manager で ONTAP クラスタを検出したら、作業環境を開いてストレージをプロビジョニングします。 


| 分析する内容に応じて、ストレージシステムの健全性属性を 2 つの方法で分析します。ダッシュボードで健全性属性ウィジェットを選択するか、すべて表示を選択して健全性属性のリスト全体を表示します。 | システムのウェルネス属性を分析するには、ダッシュボードでウェルネス属性ウィジェットを選択するだけです。または、 1 つのビューにウェルネス属性の全リストが表示される場合は、 [ すべて表示 ] を選択します。 | ダッシュボードで健全性属性ウィジェットを選択するか、すべて表示を選択してすべてのアクションとリスクのリストを表示します。 


| セットアップウィザードが起動したら、ウィザードの指示に従ってノードをセットアップし、クラスタに追加します。以下に、ウィザードでの手順を示します。 | セットアップウィザードが表示されます。このウィザードで、ノードを設定してクラスタに追加する簡単な手順を説明します。 | セットアップウィザードの手順に従ってノードをセットアップし、クラスタに追加します。 


| 新しいシステムのインストールとセットアップには、複数のコンテンツ形式から選択できます。各フォーマットタイプは、詳細な手順を提供します。学習方法に最も近い形式を選択してください。 | システムをどのようにセットアップしてインストールしますか？複数のコンテンツ形式での手順を説明しますが、学習方法は知っているものだけです。 | システムの設置とセットアップをガイドするコンテンツフォーマットタイプを選択します。 
|===


== 簡単に記入してください

複雑で大きな言葉は避けてください。シンプルに管理あなたは専門の同僚に何かを説明していますが、語彙は表示されません。

** これではなく ** 「 NetApp Cloud Central アカウントからユーザを削除する」

** これを実行 ** ：「 NetApp Cloud Central アカウントからユーザを削除してください」



== 最小限の情報を書き込みます

短い簡潔な文章で、コンテンツの読み取りやスキャンが簡単になります。より長い文章を今すぐ使用しても問題ありませんが、より短い文章をフォローしてください。いいですね。

** これよりも ** ：「 AWS および他のネットワークの ONTAP システムの Cloud Volumes ONTAP システム間でデータをレプリケートするには、 Amazon VPC と他のネットワーク（たとえば、 Azure VNet または企業ネットワーク）間に VPN 接続が必要です。」

** これを実行 **: 「ネットワーク間のデータレプリケーションには VPN 経由の接続が必要です。たとえば、 Amazon VPC と企業ネットワークの間、または AWS と Azure の間などです。」

も参照してください <<ミニマリズム>>。



== 積極的に書く

受動的な声を避けることは技術的な記述のための標準的な規則であるが、会話をしたいときは特に活動的な声を使用することは重要である。

** この ** ではなく ** ：「最初のクラスタを展開する前に、必要な権限を提供する必要があります。」

** これを実行 **: 「最初のクラスタを展開する前に、必要な権限を指定してください。」

も参照してください <<アクティブな音声（「パッシブな音声」とは対照的）>>。



== 包括的な言語を使用します

ネットアップは、製品ドキュメントに記載されている言語を差別化して排他的に使用することはできないと考えてい私たちが使用する言葉は、お客様との良好な関係を築くことと、お客様を離れさせることの違いを生み出すことができます。特に、言葉を書くと、意図よりもインパクトが重要になります。

ネットアップ製品のコンテンツを作成する際には、デグレード、人種差別、表現力の低下と解釈される言語は使用しないでください。その代わりに、ドキュメントを使用する必要があるすべてのユーザーにアクセスして歓迎される言語を使用してください。たとえば、「マスター / スレーブ」ではなく「プライマリ / セカンダリ」と指定します。

すべての非包括的な言語をドキュメントや製品から削除するために、私たちは取り組んでいることを知っています。現在は、当社の標準とベストプラクティスに積極的に取り組んでおり、将来的に追加のガイダンスを提供してこのセクションを更新する予定です。



== その点に到達します

まず、ユーザーにとって重要なことから始めます。ユーザが何をしようとしているかを調べ、その目標を達成するための支援に焦点を当てます。

** これよりも ** ： Cloud Sync では、転送中のデータ暗号化を使用して、ある NFS サーバから別の NFS サーバにデータを同期できます。データを暗号化すると、ネットワーク上でデータを転送するための厳格なセキュリティポリシーがある場合に役立ちます。」

** これを実行 **: 「企業が厳格なセキュリティポリシーを持っている場合は、転送中のデータ暗号化を使用して、異なるネットワーク上の NFS サーバ間でデータを同期します。」



== 多くのビジュアル要素を使用します

ほとんどの人は視覚的な学習者である。ビデオ、図、スクリーンショットを使用して、学習を促進します。また、ビジュアル要素はテキストのブロックを分割するのにも役立ちます。

.例
* https://docs.netapp.com/us-en/occm/concept_accounts_aws.html["例 1"^]
* https://docs.netapp.com/us-en/occm/task_getting_started_azure.html["例 2"^]


も参照してください <<グラフィックス>>。



== スキャン可能なコンテンツを作成します

見出し、リスト、および表を使用して、ユーザーが必要なものを検索できるようにします。

.例
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["例 1"^]
* https://docs.netapp.com/us-en/cloud_volumes/aws/reference_selecting_service_level_and_quota.html["例 2"^]




== ユーザの目標やその目標の特定の側面に焦点を当てます

一連のタスクの実行方法を説明している場合は、概念や参照ベースの情報など、一連のセクションのすべてのページを 1 つのページにまとめます。ページをいくつかのミニページに分割しないでください。そのためには、クリックが多すぎます。同時に、長い、威圧的なページを作成しないでください。ページが長すぎる場合は、最善の判断で決定してください。

.例
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["例 1"^]
* https://docs.netapp.com/us-en/occm/concept_ha.html["例 2"^]




== ユーザーの目標に沿ってコンテンツを整理する

必要なときに必要な情報を検索できるようにユーザを支援します。コンテンツを次のように整理することで、ドキュメントの内外にできる限り迅速に配置できます。

左側ナビゲーションの最初のエントリ（高レベル）:: ユーザーが達成しようとしている目標に沿ってコンテンツを整理する。たとえば、データの利用や保護などを行います。
ナビゲーションの 2 番目のエントリ（中レベル）:: 目標を構成する幅広いタスクを中心にコンテンツを整理する。たとえば、ディザスタリカバリの設定やデータ保護の設定などを行います。
個々のページ（詳細レベル）:: 幅広いタスクを構成する個々のタスクに関連してコンテンツを整理します。各タスクは、 1 つの学習に焦点を当てたり、その幅広いタスクを実行したりすることに重点を置いています。たとえば、ディザスタリカバリの設定に必要なタスクなどです。




== グローバルユーザー向けに作成します

当社は世界中のお客様とパートナー様に情報を提供しています。当社のコンテンツの多くは、ニューラル機械翻訳ツールまたは人間による翻訳を使用して翻訳されています。わかりやすく、翻訳を容易にするには、次のガイドラインに従ってください。

* 短い簡潔な文を書く。
* 標準の文法と句読点を使用します。
* 1 つの意味に 1 つの単語を使用し、 1 つの単語に 1 つの意味を使用します。
* 共通の収縮を使用します。
* グラフィックを使用してテキストを明確にするか、置換します。
* グラフィックにテキストを埋め込むことは避けてください。
* 1 つの文字列に 3 つ以上の名詞を含めないでください。
* 不明な許可を受けないようにします。
* 専門用語、口語、および比喩は避けてください。
* テクニカル以外の例は避けてください。
* ハードリターンと間隔を使用しないでください。
* ユーモアや皮肉を使わないでください。
* 差別的なコンテンツは使用しないでください。
* 特定のペルソナに向けて作成する場合を除き、性別に偏った言語を使用しないでください。




== A~Z のガイドラインです



=== アクティブな音声（「パッシブな音声」とは対照的）

アクティブな音声では、文の主題はアクションの doer です。

* システムを不適切にシャットダウンすると、インターフェイスに警告メッセージが表示されます。
* ネットアップは契約を受領しました。


アクティブな音声で、明瞭かつ鮮明に表現できます。パッシブボイスを使用する理由がない限り、アクティブな音声およびアドレスユーザを「自分」として直接使用します。

受動的な声では、行動の doer は不明である：

* システムが正しくシャットダウンされていない場合は、警告メッセージが表示されます。
* ネットアップは契約を獲得しました。


次の場合にパッシブボイスを使用：

* アクションを実行したユーザーや実行した内容がわからない。
* アクションの結果に対するユーザーの責任を回避したい場合。
* 前提条件に関する情報など、その情報を記述することはできません。


その他の動詞の規則については、次を参照してください。

* https://docs.microsoft.com/en-us/style-guide/welcome/["『 Microsoft Writing Style Guide 』"^]
* https://www.chicagomanualofstyle.org/home.html["シカゴ・マニュアル・オブ・スタイル"^]
* https://www.merriam-webster.com/["Merriam - Webster の辞書オンライン"^]




=== モニター

次のラベルを使用して、メインコンテンツフローとは別にコンテンツを識別します。

* 注
+
テキストの他の部分と区別する必要がある重要な情報には、メモを使用します。ユーザーがタスクについて学習したり、タスクを完了したりするために必要としない「知るべき情報」については、メモを使用しないでください。

* ヒント
+
ヒントは、デフォルトで常にベストプラクティス情報を文書化するというポリシーであるため、慎重に使用してください。必要に応じて、ヒントを使用して、ユーザーが製品を使用したり、ステップやタスクを簡単かつ効率的に完了したりするのに役立つベストプラクティス情報を含めます。

* 注意
+
死亡や重傷につながることのない原因の人身事故を引き起こす可能性がある条件や手順について、ユーザに警告するときは注意してください。





=== 導入後（「 1 回」）

* 「後」を使用して年代を示します。「電源を入れてからコンピュータを起動します。」
* 「 1 回」のみを「 1 回」を意味します。




=== また

* 「追加」を意味するには、「も」を使用します。
* 「または」を意味するために「また」を使用しないでください。




=== および / または

用語がある場合は、より正確な用語を選択します。どちらの用語も他の用語より正確でない場合は、「 AND / OR 」を使用します。



=== として

「理由」を意味するために「 As 」を使用しないでください。



=== を使用する（「使用」または「 with 」を使用する）

* を使用しているエンティティが件名である場合は、「を使用して」を使用します。「コンポーネント」メニューを使用して、新しいコンポーネントをリポジトリに追加できます。」
* 文中の先頭には、「 using 」または「 with 」を使用できます。これらの文は、製品名に応じて使用できます。「 Using SnapDrive 、 you can manage virtual disks and Snapshot copies in a Windows environment. 」




=== 可能（「かもしれない」、「かもしれない」、「すべき」、「すべき」、「すべき」）

* 「 CAN 」を使用して、機能を示します。「この手順の実行中はいつでも変更をコミットできます。」
* 「複数のプログラムをダウンロードすると処理時間に影響する可能性がある」という状況を示すには、「次の場合があります」を使用します
* 「場合によっては」を使用しないでください。これは、機能または権限のどちらかを意味する可能性があるため、あいまいです。
* 推奨されているがオプションのアクションを示すには、「すべき」を使用します。代わりに、「推奨」などの別のフレーズを使用することを検討してください。
* 「必須」はパッシブなので使用しないでください。命令的な音声を使用して、思考を命令として再調整することを検討してください。「必須」を使用する場合は、これを使用して必要なアクションまたは条件を指定します。




=== 資本金

ほとんどすべての場合、文スタイルの大文字と小文字を使用します。大文字のみ：

* 表の見出しを含む、センテンスと見出しの最初の単語
* 文の断片を含むリスト項目の最初の単語
* 適切な名詞
* ドキュメントのタイトルと字幕（ 5 文字以上の主な単語や前の位置をすべて大文字にする）
* UI 要素。ただし、インターフェイス内で大文字になっている場合に限ります。それ以外の場合は小文字を使用します。




=== 注意事項

死亡や重傷につながることのない原因の人身事故を引き起こす可能性がある条件や手順について、ユーザに警告するときは注意してください。

を参照してください <<モニター>> メインコンテンツフローとは別にコンテンツを識別する他のラベル。



=== 一貫性

「プロフェッショナルな同僚に何かを説明しているときは、あなたが話しているように書きます」とは、全員が違うことを意味します。アバナードのプロフェッショナルな会話スタイルは、ユーザーとのつながりを支援し、複数の貢献者の間で軽微な不整合の頻度を高めます。

* コンテンツを明確にして使いやすくすることに重点を置いています。すべてのコンテンツが明確で使いやすい場合、若干の不整合は問題になりません。
* 作成しているページ内で一貫性を保ちます。
* のガイドラインに必ず従ってください <<グローバルユーザー向けに作成します>>。




=== 収縮

収縮は会話の口調を補強し、多くの収縮は理解し、翻訳することが容易である。

* これらのような収縮を使い、理解しやすく、翻訳も簡単です。
+
|===


| ありません | あなたはです 


| ありません | ネットアップは 


| はいませんでした | それはある 


| ありませんでした | それでは 


| 分かりませんでした | （将来の緊張が必要な場合） 


| ありません | できない（将来の緊張が必要な場合） 


| しないでください | 将来の緊張感が必要な場合は、 
|===
* これらのような逆収縮は、理解して翻訳するのが難しいため使用しないでください。
+
|===


| 可能性があります | 必要です 


| お持ちではありません | お持ちではありません 


| 可能性もあります | できませんでした 
|===




=== （「確認」または「検証」とは対照的に）

* 「確認」を使用して、「確認」を意味します。 必要に応じて、「それ」を含めます。「図の周囲に十分な白いスペースがあることを確認してください。」
* 「確認」は、約束や保証を意味するものではありません。「 ONTAP クラスタで NFS ボリュームと CIFS ボリュームをプロビジョニングできるように、 Cloud Manager を使用してください」
* すでに存在するものや、すでに発生しているものを再度確認する必要がある場合は、「 confirm 」または「 verify 」を使用します。「 NFS がクラスタ上に設定されていることを確認します」




=== グラフィックス

コンテンツに役立つイラスト、図、フローチャート、スクリーンキャプチャ、その他の視覚的な参考資料などが含まれているかどうかを継続的に評価します。グラフィックは、複雑な概念や手順をテキストよりも明確に表します。

* 図の説明の概要を含めてください。「次の図は、背面パネルの AC 電源装置の LED を示しています。
* 図の位置を「上」または「下」ではなく、「下」または「上」または「前」と参照してください。




=== 文法

特に明記されていない限り、文法、句読点、および次の表記法に従ってください。

* https://docs.microsoft.com/en-us/style-guide/welcome/["『 Microsoft Writing Style Guide 』"^]
* https://www.chicagomanualofstyle.org/home.html["シカゴ・マニュアル・オブ・スタイル"^]
* https://www.merriam-webster.com/["Merriam - Webster の辞書オンライン"^]




=== そうでない場合は

以前の文を参照するために、「そうでない場合」だけを使用しないでください。

** この ** ではなく ** ： " コンピュータはオフになっている必要があります。そうでない場合は、オフにします。」

** これを実行 ** ： " コンピュータがオフになっていることを確認してください。 "



=== IF （「いつ」または「いつ」のどちらか）

* 「 If this 、 then that 」構文などの条件を指定するには、「 if 」を使用します。
* 指定された条件または暗黙の条件がある場合は、「どうか」を使用します。翻訳を容易にするためには、「どうか」を単独で置き換えるのが最適です。
* 時間の経過を示すには、「 when 」を使用します。




=== 命令的な音声

* ユーザアクションのリストには、ステップ、ディレクティブ、要求、および見出しに imperative voice を使用します。
+
** 「 [Working Environments （作業環境） ] ページで、 [Discover （検出） ] をクリックし、 ONTAP Cluster （クラスタの検出）を選択
** 「カムハンドルを回して、電源装置と同一面になるようにします。」


* パッシブボイスの代わりに必ず音声を使用することを検討してください。
+
** この ** ではなく ** ：「最初のクラスタを展開する前に、必要な権限を提供する必要があります。」

+
** これを実行 **: 「最初のクラスタを展開する前に、必要な権限を指定してください。」

* 概念的な情報とリファレンス情報に手順を組み込む場合は、 imperative voice を使用しないでください。




=== IP アドレスと IPv6 アドレス

たとえば、 IP アドレス（ IPv6 を含む）の場合は、「 10.x 」で始まるアドレスを含めても安全です。



=== 今後の機能またはリリース

今後リリースされる製品や機能のタイミングや内容を参照しないでください。ただし、機能が「現在サポートされていません」である場合を除く。



=== 技術情報アーティクル：「 Referring to

該当する場合は、 KB （ネットアップナレッジベース）記事を参照してください。リソースページおよび GitHub コンテンツの場合は、リンクを実行中のテキストに配置します。



=== リスト

情報のリストは、通常、テキストのブロックよりもスキャンして吸収する方が簡単です。複雑な情報をリスト形式で表示することで、単純化する方法を検討します。以下に一般的なガイドラインをいくつか示しますが、あなたの判断を使用してください。

* リストの理由が明確であることを確認します。完全な文、コロン付きの文、または見出しでリストを紹介します。
* リストには 2 ～ 7 のエントリが必要です。一般に、各エントリの情報が短いほど、リストをスキャン可能なまま追加できるエントリが増えます。
* リストエントリは、できる限りスキャン可能にする必要があります。リストエントリをスキャン可能な状態に保つ方法でテキストのブロックを避けます。
* リストエントリは大文字で開始する必要があり、リストエントリは文法的に平行である必要があります。たとえば、名詞または動詞を使用して各エントリを開始します。
+
** すべてのリストエントリが完全な文の場合は、ピリオドで終了します。
** すべてのリストエントリが文の断片の場合は、ピリオドで終了しないでください。


* リストエントリは、アルファベット順や年代順に並べ替える必要があります。




=== ローカリゼーション

を参照してください <<グローバルユーザー向けに作成します>>。



=== ミニマリズム

* この時点で、ユーザーはこのコンテンツを必要としていますか？
* あまり形式的でない、またはあまりにカジュアルではなく、より少ない言葉でコンテンツを表示できますか？
* 長い文章を短くしたり、単純化したり、 2 つ以上の文章に分割することはできますか？
* リストを使用して、コンテンツをスキャン可能にできますか。
* グラフィックを使用してテキストブロックを補強または置換できますか。




=== NOTE 情報

テキストの他の部分と区別する必要がある重要な情報には、メモを使用します。ユーザーがタスクについて学習したり、タスクを完了したりするために必要としない「知るべき情報」については、メモを使用しないでください。

を参照してください <<モニター>> メインコンテンツフローとは別にコンテンツを識別する他のラベル。



=== 数字

* 次の例外を除いて、 10 以上のすべての数値にアラビア数字を使用します。
+
** 文字列の先頭に数字を使用する場合は、アラビア数字ではなく、単語を使用します。
** 概算の数値には（数字ではなく）単語を使用します。


* 10 未満の数字には単語を使用します。
* 10 未満の数字と 10 を超える数字が混在する文がある場合は、すべての数字にアラビア数字を使用します。
* その他の番号の表記法については、次を参照してください
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["『 Microsoft Writing Style Guide 』"^]
** https://www.chicagomanualofstyle.org/home.html["シカゴ・マニュアル・オブ・スタイル"^]






=== 多賀主義

ネットアップの製品、およびネットアップ製品とサードパーティ製品との連携について記載します。サードパーティ製品は文書化しません。サードパーティのコンテンツをコピーしてドキュメントに貼り付ける必要はなく、絶対にコピーしないでください。



=== 前提条件

前提条件は、存在する必要がある条件、または現在のタスクを開始する前にユーザが完了しておく必要がある操作を示します。

* 「前提条件」、「開始前」、「開始前」などの見出しを持つコンテンツの性質を識別します。
* 前提条件の言葉にパッシブな声を使用することが妥当な場合は、次のようにします。
+
** クラスタに NFS または CIFS を設定する必要があります。
** クラスタを Cloud Manager に追加するには、クラスタ管理 IP アドレスと admin ユーザアカウントのパスワードが必要です。


* 必要に応じて、前提条件を明確にします。「 NFS または CIFS をクラスタにセットアップする必要があります。System Manager または CLI を使用して、 NFS と CIFS を設定できます。
* 他の方法で情報を提示することも検討してください。たとえば、現在のタスクの最初のステップとしてコンテンツをリワードするのが適切かどうかを検討します。
+
** 前提条件：「最初のクラスタを導入する前に、必要な権限を持っている必要があります。」
** 手順：「最初のクラスタを展開するために必要な権限を指定します。」






=== 以前（「前」、「前」、または「前」）

* 可能であれば、「前」を「前」に置き換えます。
* 「前」を使用できない場合は、「前」を形容詞として使用して、以前に発生したことや重要度の高いことを参照します。
* 「前へ」を使用して、事前に指定されていない時間に発生したことを示します。
* 「先行」を使用して、事前に発生したことを示します。




=== 句読点

シンプルに管理一般に、文章に含まれる句読点が多いほど、理解するために必要な脳細胞が増えます。

* 3 つ以上の品目の説明リストで、組み合わせ（「 AND 」または「 OR 」）の前にシリアルカンマ（ Oxford コンマ）を使用します。
* セミコロンとコロンの使用を制限します。
* 特に明記されていない限り、文法、句読点、および次の表記法に従ってください。
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["『 Microsoft Writing Style Guide 』"^]
** https://www.chicagomanualofstyle.org/home.html["シカゴ・マニュアル・オブ・スタイル"^]
** https://www.merriam-webster.com/["Merriam - Webster の辞書オンライン"^]






=== 以来

「経過時間」を示すには、「経過時間」を使用します。「理由」を意味するために「以降」を使用しないでください。



=== スペルチェック

特に明記されていない限り、文法、句読点、および次の表記法に従ってください。

* https://docs.microsoft.com/en-us/style-guide/welcome/["『 Microsoft Writing Style Guide 』"^]
* https://www.chicagomanualofstyle.org/home.html["シカゴ・マニュアル・オブ・スタイル"^]
* https://www.merriam-webster.com/["Merriam - Webster の辞書オンライン"^]




=== それ（「誰が」）

* （末尾にカンマを入れずに）「 that 」を使用して、文が意味を持つようにするために必要な句を説明します。
* 「その」は、文章が英語ではなくても使用します。「コンピュータがオフになっていることを確認します。」
* 補足情報を追加するが、意味を持たせるために文には必要ない句を導入するには、“ which ”（末尾にカンマを付けて）を使用します。
* 「誰」を使用して、人を参照する句を紹介します。




=== TIP 情報

ヒントは、デフォルトで常にベストプラクティス情報を文書化するというポリシーであるため、慎重に使用してください。必要に応じて、ヒントを使用して、ユーザーが製品を使用したり、ステップやタスクを簡単かつ効率的に完了したりするのに役立つベストプラクティス情報を含めます。

を参照してください <<モニター>> メインコンテンツフローとは別にコンテンツを識別する他のラベル。



=== 商標

ほとんどの技術コンテンツには商標記号は含まれていません。これは、テンプレートに記載されている法的記述が十分であるためです。ただし、を使用する場合は、すべての使用規則に従ってください https://www.netapp.com/us/legal/netapptmlist.aspx["ネットアップの商標"^]：

* 商標用語は、形容詞としてのみ使用し、名詞、動詞、または口頭として使用しないでください。
* 商標用語を省略、ハイフンで区切る、または斜体にしないでください。
* 商標のある用語を盗もうとしないでください。複数形が必要な場合は、商標名を形容詞として使用し、複数形名詞を修正します。
* 商標用語の独占的形式は使用しないでください。ネットアップなど、ネットアップの会社名は、商標登録用語ではなく一般的な意味で使用されている場合に、独占的な形式を使用できます。




=== ユーザインターフェイス

ユーザを誘導するには、可能な限りインターフェイスを使用します。



==== 一般的なガイドライン

当社の UI 文書化のスタイルはシンプルで最小限です。

* ユーザーがコンテンツの読み取り中にインターフェイスを使用しているとします。
* ユーザをガイドするには、インターフェイスを使用します。
+
** ユーザーがウィザードや画面の手順を一歩ずつ進めないようにしてください。インターフェイスから明確でない重要な事項のみを呼び出します。
** 「 OK 」をクリックしたり、「保存」をクリックしたり、「ボリュームが作成されている」、またはタスクを実行している人にとって明らかなその他のものを含めないでください。
** 成功を想定します。ほとんどの場合、処理が失敗すると予想される場合を除き、障害パスは文書化しないでください。インターフェイスが適切なガイダンスを提供しているとします。


* 「クリック」は使わないでください。マウス、タッチ、キーボード、その他の選択方法をカバーするため、必ず「 SELECT 」を使用してください。
* お客様のユースケースに対応し、ワークフローを開始するためにユーザをインターフェイス内の適切な場所に配置するためのワークフローに、コンテンツを集中的に配置します。
* ユーザーの目標を達成するための最良の方法の 1 つを常に文書化してください。
* ワークフローで重大な決定が必要な場合は、必ず決定規則を文書化してください。
* ほとんどのユーザには、最低限必要な手順を使用します。




==== UI 要素に名前を付ける

UI 要素に名前を付ける必要がある細分性レベルにドキュメント化しないでください。インターフェイスを使用して、インタラクションの詳細をユーザーに説明します。特定のラベルを取得する必要がある場合は、そのラベルに名前を付けます。たとえば、「目的のボリュームを選択」または「既存のボリュームを使用」を選択します。 メニューやラジオボタン、またはチェックボックスに名前を付ける必要はありません。ラベルを使用してください。

ユーザーが選択する必要があるアイコンの場合は、アイコンの画像を使用します。名前を付けないでください。このルール環境では、矢印、鉛筆、ギア、 kabob 、ハンバーガー、 など。



==== 表示されているラベルを表します

ラベルを識別するときは、ユーザインターフェイスで使用されるスペルと大文字小文字の区別に従ってください。ラベルの後ろに省略記号が付いている場合は、オブジェクトの名前に省略記号を含めないでください。ユーザインターフェイスラベルにタイトルスタイルの大文字と小文字を使用して、ユーザインターフェイスラベルについて簡単に記述できるようにするように開発者に勧めてください。



==== スクリーンキャプチャを使用する

スクリーンキャプチャ（「スクリーンショット」）は、ワークフロー中にインターフェイスを開始または変更するときに、インターフェイス内の適切な場所にいることをユーザが確信できるようにします。入力するデータや選択する値をスクリーンキャプチャで表示しないでください。



=== 一時的（「はい」）

* 「 While 」を使用して、時間内に発生していることを示します。
* 「はい」を使用して、ほぼ同じ時間に発生する、または別のアクティビティの直後に発生するアクティビティを表します。




=== ワークフロー

ユーザーはコンテンツを読み、特定の目標を達成します。ユーザーは、必要なコンテンツを検索し、目標を達成し、家族に向けて家に帰りたいと考えています。当社の仕事は製品や機能を文書化することではなく、ユーザーの目標を文書化することです。ワークフローは、ユーザの目標達成を支援する最も直接的な方法です。

ワークフローとは、ユーザの目標を達成する方法を説明する一連のステップまたはサブタスクです。ワークフローの範囲は完全な目標です。

たとえば、ボリューム自体での作成は完全な目標ではないため、ボリュームの作成手順はワークフローにはなりません。ESX サーバでストレージを使用できるようにする手順は、ワークフローになります。この手順には、ボリュームの作成だけでなく、ボリュームのエクスポート、必要な権限の設定、ネットワークインターフェイスの作成などが含まれます。ワークフローは、お客様のユースケースに基づいています。ワークフローは、目標を達成するための最良の方法を 1 つだけ示しています。
